version: '3.6'
services:
  ai-european-football-api:
    build:
      dockerfile: docker_api/Dockerfile
    ports:
      - "84:80"
      - "8804:8800"
    volumes:
      - ./docker_api:/ai_european_football/docker_api
    command: [ "sh", "-c",  "cd /ai_european_football/docker_api && uvicorn api.main:api --host 0.0.0.0 --port 80 --reload" ]
# Additionally, running the jupyterlab
#    command: [ "sh", "-c",  "cd /ai_european_football/docker_api && uvicorn api.main:api --host 0.0.0.0 --port 80 --reload & jupyter lab --port=8800 --no-browser --ip=* --allow-root" ]

  ai-european-football-backend-tf2-16:
    build:
      dockerfile: docker_tf2_16/Dockerfile.macos
    ports:
      - "40216:80"
      - "47216:47216"
    volumes:
      - ./docker_tf2_16:/ai_european_football/docker_tf2_16
#    command: [ "sh", "-c",  "cd /ai_european_football/docker_tf2_16 && uvicorn app.main:app --host 0.0.0.0 --port 80 --reload" ]
# Additionally, running the jupyterlab
    command: [ "sh", "-c",  "cd /ai_european_football/docker_tf2_16 && uvicorn app.main:app --host 0.0.0.0 --port 80 --reload & jupyter lab --port=47216 --no-browser --ip=* --allow-root" ]
