#########################################################################################
#   ___  _ _    ___          _             ___      _ _    _
#  / _ \| | |  |   \ ___  __| |_____ _ _  | _ )_  _(_) |__| |
# | (_) |_  _| | |) / _ \/ _| / / -_) '_| | _ \ || | | / _` |
#  \__\_\ |_|  |___/\___/\__|_\_\___|_|   |___/\_,_|_|_\__,_|
#
#  NOTE: DO NOT USE CONTAINER ENV VARS IN THIS FILE!!!
#
#  This file is used to build the containers for distribution. Any ENV vars used
#  herein will be permanently applied to the distributed container!!!
#
#  @see docker-compose.yml for installation configuration.
#
#  Pushing builds to remote ECR repos:
#
#  Ensure you have installed the latest version of the AWS CLI and Docker.
#  For more information, see the ECR documentation:
#  http://docs.aws.amazon.com/AmazonECR/latest/userguide/ECR_GetStarted.html
#
#  Retrieve the login command to use to authenticate your Docker client to your registry.
#  Use the AWS CLI:
#
#    $(aws ecr get-login --no-include-email --region ca-central-1)
#
#  Build your Docker image using the commands above.
#
#  Push all images in the docker-compose file using:
#
#    docker-compose -f docker-compose.build.yml push
#
#########################################################################################

version: '3.6'

services:

  ai-european-football-api:
    image: "314646722731.dkr.ecr.ca-central-1.amazonaws.com/q4/io_quarter4_prediction_european_football_api:${CI_GIT_BRANCH_TYPE_NAME}"
    build:
      context: .
      dockerfile: docker_api/Dockerfile

  ai-european-football-backend-tf2-16:
    image: "314646722731.dkr.ecr.ca-central-1.amazonaws.com/q4/io_quarter4_prediction_european_football_tf2_16:${CI_GIT_BRANCH_TYPE_NAME}"
    build:
      context: .
      dockerfile: docker_tf2_16/Dockerfile
