create table mlb_pregame_odds
(

id 					varchar(255),
sportsbook		 	varchar(50),
market				varchar(50),
name				varchar(50),
is_main				varchar(50),
selection			varchar(100),
normalized_selection	varchar(100),
market_id			varchar(100),
selection_line		varchar(50),
player_id			varchar(50),
team_id				varchar(50),
price				float,
timestamp			float,
grouping_key		varchar(50),
points				float,
game_id				varchar(75),
updated_at        timestamp default current_timestamp() on update current_timestamp(),
primary key (game_id, sportsbook, market, name)
)
collate utf8mb3_general_ci
;

create table mlb_live_odds
(

id 					varchar(255),
sportsbook		 	varchar(50),
market				varchar(50),
name				varchar(50),
is_main				varchar(50),
selection			varchar(100),
normalized_selection	varchar(100),
market_id			varchar(100),
selection_line		varchar(50),
player_id			varchar(50),
team_id				varchar(50),
price				float,
timestamp			float,
grouping_key		varchar(50),
points				float,
game_id				varchar(75),
updated_at        timestamp default current_timestamp() on update current_timestamp(),
primary key (game_id, sportsbook, market, name)
)
collate utf8mb3_general_ci
;


create table mlb_pbp
(
game_id						int(11),
at_bat_index				int(11),
ab_start_time				varchar(50),
ab_end_time					varchar(50),
inning						int(11),
half_inning					varchar(50),
is_complete					BOOLEAN,
event_type					varchar(50),
play_event_description		varchar(500),
batter_id					int(11),
batter_name					varchar(50),
pitcher_id					int(11),	
pitcher_name				varchar(50),
pitcher_hand				varchar(50),
batter_side					varchar(50),
result_type					varchar(50),
play_result_event			varchar(50),
play_result_description		varchar(500),
rbi							int(11),
home_score					int(11),
away_score					int(11),
is_out						BOOLEAN,
balls						int(11),
strikes						int(11),
outs						int(11),
pitch_number				int(11),
call_code					varchar(50),
call_description			varchar(50),
pitch_type					varchar(50),
pitch_code					varchar(50),
ball_color					varchar(50),
trail_color					varchar(50),
is_in_play					BOOLEAN,
is_strike					BOOLEAN,
is_ball						BOOLEAN,
play_balls					int(11),	
play_strikes				int(11),
play_outs					int(11),
start_speed					float,
end_speed					float,
strike_zone_top				float,
strike_zone_zottom			float,
zone						int(11),
plate_time					float,
extension					float,
break_angle					float,
break_length				float,
break_vertical				float,
break_vertical_induced		float,
break_horizontal			float,
spin_rate					float,
spin_direction				float,
launch_speed				float,
launch_angle				float,
total_distance				float,
trjaectory					varchar(50),
hardness					varchar(50),
location					float,
hit_x						float,
hit_y						float,
runner1_id					int(11),
runner1_name				varchar(50),
runner1_start				varchar(50),
runner1_end					varchar(50),
runner1_out_base			varchar(50),
runner1_is_out				varchar(50),
runner1_credit_rbi			varchar(50),
runner1_credit_earned		varchar(50),
runner1_event				varchar(50),
coordinates_ay				float,
coordinates_az				float,
coordinates_pfxx			float,
coordinates_pfxz			float,
coordinates_px				float,
coordinates_pz				float,
coordinates_vx0				float,
coordinates_vy0				float,
coordinates_vz0				float,
coordinates_x				float,
coordinates_y				float,
coordinates_x0				float,
coordinates_y0				float,
coordinates_z0				float,
coordinates_ax				float,
runner2_id					int(11),
runner2_name				varchar(50),
runner2_start				varchar(50),
runner2_end					varchar(50),
runner2_out_base			varchar(50),
runner2_is_out				varchar(50),
runner2_credit_rbi			varchar(50),
runner2_credit_earned		varchar(50),
runner2_event				varchar(50),
runner3_id					int(11),
runner3_name				varchar(50),
runner3_start				varchar(50),
runner3_end					varchar(50),
runner3_out_base			varchar(50),
runner3_is_out				varchar(50),
runner3_credit_rbi			varchar(50),
runner3_credit_earned		varchar(50),
runner3_event				varchar(50),
runner4_id					int(11),	
runner4_name				varchar(50),
runner4_start				varchar(50),
runner4_end					varchar(50),
runner4_out_base			varchar(50),
runner4_is_out				varchar(50),
runner4_credit_rbi			varchar(50),
runner4_credit_earned		varchar(50),
runner4_event				varchar(50),
runner5_id					int(11),
runner5_name				varchar(50),
runner5_start				varchar(50),
runner5_end					varchar(50),
runner5_out_base			varchar(50),
runner5_is_out				varchar(50),
runner5_credit_rbi			varchar(50),
runner5_credit_earned		varchar(50),
runner5_event				varchar(50),
runner6_id					int(11),
runner6_name				varchar(50),
runner6_start				varchar(50),
runner6_end					varchar(50),
runner6_out_base			varchar(50),
runner6_is_out				varchar(50),
runner6_credit_rbi			varchar(50),
runner6_credit_earned		varchar(50),
runner6_event				varchar(50),
updated_at        timestamp default current_timestamp() on update current_timestamp(),
primary key (game_id, inning, batter_id, pitcher_id, pitch_number)
)
collate utf8mb3_general_ci
;



USE mlb_jalen;
create table mlb_schedule
(
game_id						int(11),
game_datetime				varchar(50),
game_date					varchar(50),
home_abbr					varchar(50),
away_abbr					varchar(50),
home_id						int(11),
away_id						int(11),
home_team					varchar(50),
away_team					varchar(50),
status						varchar(50),
game_type					varchar(50),
double_header				varchar(50),
game_num					int(11),
away_lineup					JSON,
home_lineup					JSON,
updated_at        timestamp default current_timestamp() on update current_timestamp(),
primary key (game_id, game_num)
)
collate utf8mb3_general_ci
;


USE mlb_jalen;
create table mlb_box_score_batter
(
id								int(11),
game_id							int(11),
name							VARCHAR(255),
position						VARCHAR(50),
location						VARCHAR(50),
team							VARCHAR(50),
batting_summary					VARCHAR(50),
batting_gamesplayed				float,
batting_flyouts	float,
batting_groundouts	float,
batting_airouts	float,
batting_runs	float,
batting_doubles	float,
batting_triples	float,
batting_homeruns	float,
batting_strikeouts	float,
batting_baseonballs	float,
batting_intentionalwalks	float,
batting_hits	float,
batting_hitbypitch	float,
batting_atbats	float,
batting_caughtstealing float,	
batting_stolenbases		float,
batting_groundintodoubleplay	float,
batting_groundintotripleplay float,	
batting_plateappearances	float,
batting_totalbases	float,
batting_rbi	float,
batting_leftonbase	float,
batting_sacbunts	float,
batting_sacflies	float,
batting_catchersinterference	float,
batting_pickoffs		float,
batting_popouts	float,
batting_lineouts	float,
fielding_gamesstarted float,	
fielding_caughtstealing	float,
fielding_stolenbases	float,
fielding_assists	float,
fielding_putouts	float,
fielding_errors	float,
fielding_chances	float,
fielding_fielding	float,
fielding_passedball	float,
fielding_pickoffs	float,
updated_at        timestamp default current_timestamp() on update current_timestamp(),
primary key (game_id, id)
)
collate utf8mb3_general_ci
;

create table mlb_box_score_pitcher
(
game_id int(11),
id int(11),
name VARCHAR(50),
position VARCHAR(50),
location VARCHAR(50),
team VARCHAR(50),
pitching_summary VARCHAR(50),
pitching_gamesplayed float,
pitching_gamesstarted float,
pitching_flyouts float,
pitching_groundouts float, 
pitching_airouts float,
pitching_runs float,
pitching_doubles float,
pitching_triples float,
pitching_homeruns float,
pitching_strikeouts float,
pitching_baseonballs float,
pitching_intentionalwalks float,
pitching_hits float,
pitching_hitbypitch float,
pitching_atbats float,
pitching_caughtstealing float,
pitching_stolenbases float,
pitching_numberofpitches float,
pitching_inningspitched float,
pitching_wins float,
pitching_losses float,
pitching_saves float,
pitching_saveopportunities float,
pitching_holds float,
pitching_blownsaves float,
pitching_earnedruns float,
pitching_battersfaced float,
pitching_outs float,
pitching_gamespitched float,
pitching_completegames float,
pitching_shutouts float,
pitching_pitchesthrown float,
pitching_balls float,
pitching_strikes float,
pitching_strikepercentage float,
pitching_hitbatsmen float,
pitching_balks float,
pitching_wildpitches float,
pitching_pickoffs float,
pitching_rbi float,
pitching_gamesfinished float,
pitching_runsscoredper9 float,
pitching_homerunsper9 float,
pitching_inheritedrunners float,
pitching_inheritedrunnersscored float,
pitching_catchersinterference float,
pitching_sacbunts float,
pitching_sacflies float,
pitching_passedball float,
pitching_popouts float,
pitching_lineouts float,
updated_at        timestamp default current_timestamp() on update current_timestamp(),
primary key (game_id, id)
)
collate utf8mb3_general_ci
;


create table mlb_box_score_team
(
team_name VARCHAR(50),
team_id INT(11),
game_id INT(11),
batting_flyouts					 float,
batting_groundouts					 float,
batting_airouts					 float,
batting_runs					 float,
batting_doubles					 float,
batting_triples					 float,
batting_homeruns					 float,
batting_strikeouts					 float,
batting_baseonballs					 float,
batting_intentionalwalks					 float,
batting_hits					 float,
batting_hitbypitch					 float,
batting_avg					 float,
batting_atbats					 float,
batting_obp					 float,
batting_slg					 float,
batting_ops					 float,
batting_caughtstealing					 float,
batting_stolenbases					 float,
batting_groundintodoubleplay					 float,
batting_groundintotripleplay					 float,
batting_plateappearances					 float,
batting_totalbases					 float,
batting_rbi					 float,
batting_leftonbase					 float,
batting_sacbunts					 float,
batting_sacflies					 float,
batting_catchersinterference					 float,
batting_pickoffs					 float,
batting_popouts					 float,
batting_lineouts					 float,
pitching_flyouts					 float,
pitching_groundouts					 float,
pitching_airouts					 float,
pitching_runs					 float,
pitching_doubles					 float,
pitching_triples					 float,
pitching_homeruns					 float,
pitching_strikeouts					 float,
pitching_baseonballs					 float,
pitching_intentionalwalks					 float,
pitching_hits					 float,
pitching_hitbypitch					 float,
pitching_atbats					 float,
pitching_obp					 float,
pitching_caughtstealing					 float,
pitching_stolenbases					 float,
pitching_numberofpitches					 float,
pitching_era					 float,
pitching_inningspitched					 float,
pitching_saveopportunities					 float,
pitching_earnedruns					 float,
pitching_whip					 float,
pitching_battersfaced					 float,
pitching_outs					 float,
pitching_completegames					 float,
pitching_shutouts					 float,
pitching_pitchesthrown					 float,
pitching_balls					 float,
pitching_strikes					 float,
pitching_strikepercentage					 float,
pitching_hitbatsmen					 float,
pitching_balks					 float,
pitching_wildpitches					 float,
pitching_pickoffs					 float,
pitching_groundoutstoairouts					 float,
pitching_rbi					 float,
pitching_pitchesperinning					 float,
pitching_runsscoredper9					 float,
pitching_homerunsper9					 float,
pitching_inheritedrunners					 float,
pitching_inheritedrunnersscored					 float,
pitching_catchersinterference					 float,
pitching_sacbunts					 float,
pitching_sacflies					 float,
pitching_passedball					 float,
pitching_popouts					 float,
pitching_lineouts					 float,
fielding_caughtstealing					 float,
fielding_stolenbases					 float,
fielding_assists					 float,
fielding_putouts					 float,
fielding_errors					 float,
fielding_chances					 float,
fielding_passedball					 float,
fielding_pickoffs					 float,
updated_at        timestamp default current_timestamp() on update current_timestamp(),
primary key (game_id, team_id)
)
collate utf8mb3_general_ci
;

create table mlb_event_meta
(
game_id						int(11),
game_datetime				varchar(50),
game_date					varchar(50),
home_id						int(11),
away_id						int(11),
home_team					varchar(50),
away_team					varchar(50),
status						varchar(50),
game_type					varchar(50),
double_header				varchar(50),
game_num					int(11),
forecast_timestamp			varchar(50),
pop_adjusted				float,
cloud_cover					float,
descr						varchar(50),
dewpoint					float,
temp_feelslike				float,
sky_condition				float,
precipitation				float,
pop							float,
precipitation_rate			float,
relative_humidity			float,
temperature					float,
thunderstorm_prob			float,
wind_direction				float,
wind_speed					float,
surface_pressure			float,



updated_at        timestamp default current_timestamp() on update current_timestamp(),
primary key (game_id)
)
collate utf8mb3_general_ci
;